### ISSUE TITLE
Ошибка 400 после падения сервера Shiki

### ISSUE THREAD

**Issue by gizmooo** [cawa-93/play-shikimori-online#138]
После смерти жесткого диска у провайдера shiki и восстановления сайта из бэкапа синхронизация аддона с сайтом прекратилась и каждый раз при попытке выходит ошибка:

Невозможно обновить access_token: Сервер ответил с ошибкой 400

**Comment by cawa-93** [comment]
Попробуйте:
1. Откройте страницу расширения
1. Откройте консоль браузера
1. Выполните `chrome.storage.sync.set({'userAuth': undefined}, console.log)`
1. Перезагрузите страницу
1. Включите синхронизацию с Шикимори.

**Comment by gizmooo** [comment]
Ставлю чекбокс на синхронизацию, закрываю окно настроек - будто не ставил.

chrome.storage отдает undefined в консоли.

**Comment by cawa-93** [comment]
Если синхронизация выключена, то вместо формы комментария должна быть кнопка "Включить синхронизацию". Попробуйте использовать её

**Comment by gizmooo** [comment]
Решилась проблема только переустановкой. После включил синхронизацию в настройках и все подтянулось)

**Comment by NesterovichAlexey** [comment]
Мне помогло `chrome.storage.sync.set({'userAuth': null}, console.log)`.
`undefined` почему-то не чистил storage. Пробовал на Я.Браузере.

**Comment by gizmooo** [comment]
null я тоже пробовал - мне не помогло
